import { SubjectCategory, Curriculum } from '../../database/entities/subject.entity';

export interface PredefinedSubject {
  name: string;
  code: string;
  category: SubjectCategory;
  curriculum: Curriculum;
  description: string;
  gradeLevelStart: number;
  gradeLevelEnd: number;
  isCompulsory: boolean;
  lessonsPerWeek?: number;
  credits?: number;
}

// CBC (Competency-Based Curriculum) - Kenya
export const CBC_SUBJECTS: PredefinedSubject[] = [
  // Pre-Primary (PP1-PP2, Grades 1-2)
  {
    name: 'Literacy Activities',
    code: 'CBC-LIT',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.CBC,
    description: 'Early literacy development through play and structured activities',
    gradeLevelStart: 1, // PP1
    gradeLevelEnd: 2, // PP2
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Mathematical Activities',
    code: 'CBC-MATH-PP',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.CBC,
    description: 'Early numeracy and problem-solving skills',
    gradeLevelStart: 1,
    gradeLevelEnd: 2,
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Environmental Activities',
    code: 'CBC-ENV',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.CBC,
    description: 'Exploring the immediate environment',
    gradeLevelStart: 1,
    gradeLevelEnd: 2,
    isCompulsory: true,
    lessonsPerWeek: 3,
  },
  {
    name: 'Psychomotor and Creative Activities',
    code: 'CBC-PSYCH',
    category: SubjectCategory.ARTS,
    curriculum: Curriculum.CBC,
    description: 'Physical development, music, art, and creative expression',
    gradeLevelStart: 1,
    gradeLevelEnd: 2,
    isCompulsory: true,
    lessonsPerWeek: 4,
  },

  // Lower Primary (Grades 1-3, Levels 3-5)
  {
    name: 'English',
    code: 'CBC-ENG-LP',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.CBC,
    description: 'English language skills - reading, writing, listening, speaking',
    gradeLevelStart: 3, // Grade 1
    gradeLevelEnd: 5, // Grade 3
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Kiswahili/Kenyan Sign Language',
    code: 'CBC-KIS-LP',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.CBC,
    description: 'Kiswahili language or Kenyan Sign Language',
    gradeLevelStart: 3,
    gradeLevelEnd: 5,
    isCompulsory: true,
    lessonsPerWeek: 4,
  },
  {
    name: 'Mathematics',
    code: 'CBC-MATH-LP',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.CBC,
    description: 'Mathematical concepts and problem-solving',
    gradeLevelStart: 3,
    gradeLevelEnd: 5,
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Integrated Science',
    code: 'CBC-SCI-LP',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.CBC,
    description: 'Basic science concepts and environmental awareness',
    gradeLevelStart: 3,
    gradeLevelEnd: 5,
    isCompulsory: true,
    lessonsPerWeek: 3,
  },
  {
    name: 'Health Education',
    code: 'CBC-HE-LP',
    category: SubjectCategory.LIFE_SKILLS,
    curriculum: Curriculum.CBC,
    description: 'Personal health, hygiene, and safety',
    gradeLevelStart: 3,
    gradeLevelEnd: 5,
    isCompulsory: true,
    lessonsPerWeek: 2,
  },
  {
    name: 'Pre-Technical Studies',
    code: 'CBC-PTS-LP',
    category: SubjectCategory.TECHNICAL,
    curriculum: Curriculum.CBC,
    description: 'Introduction to technology and practical skills',
    gradeLevelStart: 3,
    gradeLevelEnd: 5,
    isCompulsory: true,
    lessonsPerWeek: 2,
  },
  {
    name: 'Social Studies',
    code: 'CBC-SS-LP',
    category: SubjectCategory.HUMANITIES,
    curriculum: Curriculum.CBC,
    description: 'Understanding society, culture, and citizenship',
    gradeLevelStart: 3,
    gradeLevelEnd: 5,
    isCompulsory: true,
    lessonsPerWeek: 3,
  },
  {
    name: 'Religious Education',
    code: 'CBC-RE-LP',
    category: SubjectCategory.RELIGIOUS_EDUCATION,
    curriculum: Curriculum.CBC,
    description: 'Christian/Islamic/Hindu Religious Education',
    gradeLevelStart: 3,
    gradeLevelEnd: 5,
    isCompulsory: false,
    lessonsPerWeek: 2,
  },
  {
    name: 'Creative Arts',
    code: 'CBC-CA-LP',
    category: SubjectCategory.ARTS,
    curriculum: Curriculum.CBC,
    description: 'Music, art, drama, and creative expression',
    gradeLevelStart: 3,
    gradeLevelEnd: 5,
    isCompulsory: true,
    lessonsPerWeek: 3,
  },
  {
    name: 'Physical and Health Education',
    code: 'CBC-PHE-LP',
    category: SubjectCategory.PHYSICAL_EDUCATION,
    curriculum: Curriculum.CBC,
    description: 'Physical fitness, sports, and games',
    gradeLevelStart: 3,
    gradeLevelEnd: 5,
    isCompulsory: true,
    lessonsPerWeek: 3,
  },

  // Upper Primary (Grades 4-6, Levels 6-8)
  {
    name: 'English',
    code: 'CBC-ENG-UP',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.CBC,
    description: 'Advanced English language skills',
    gradeLevelStart: 6, // Grade 4
    gradeLevelEnd: 8, // Grade 6
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Kiswahili/Kenyan Sign Language',
    code: 'CBC-KIS-UP',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.CBC,
    description: 'Advanced Kiswahili or Kenyan Sign Language',
    gradeLevelStart: 6,
    gradeLevelEnd: 8,
    isCompulsory: true,
    lessonsPerWeek: 4,
  },
  {
    name: 'Mathematics',
    code: 'CBC-MATH-UP',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.CBC,
    description: 'Advanced mathematical concepts',
    gradeLevelStart: 6,
    gradeLevelEnd: 8,
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Integrated Science',
    code: 'CBC-SCI-UP',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.CBC,
    description: 'Science and technology concepts',
    gradeLevelStart: 6,
    gradeLevelEnd: 8,
    isCompulsory: true,
    lessonsPerWeek: 4,
  },
  {
    name: 'Health Education',
    code: 'CBC-HE-UP',
    category: SubjectCategory.LIFE_SKILLS,
    curriculum: Curriculum.CBC,
    description: 'Health, nutrition, and life skills',
    gradeLevelStart: 6,
    gradeLevelEnd: 8,
    isCompulsory: true,
    lessonsPerWeek: 2,
  },
  {
    name: 'Pre-Technical Studies',
    code: 'CBC-PTS-UP',
    category: SubjectCategory.TECHNICAL,
    curriculum: Curriculum.CBC,
    description: 'Technology and practical skills',
    gradeLevelStart: 6,
    gradeLevelEnd: 8,
    isCompulsory: true,
    lessonsPerWeek: 3,
  },
  {
    name: 'Social Studies',
    code: 'CBC-SS-UP',
    category: SubjectCategory.HUMANITIES,
    curriculum: Curriculum.CBC,
    description: 'History, geography, and citizenship',
    gradeLevelStart: 6,
    gradeLevelEnd: 8,
    isCompulsory: true,
    lessonsPerWeek: 3,
  },
  {
    name: 'Religious Education',
    code: 'CBC-RE-UP',
    category: SubjectCategory.RELIGIOUS_EDUCATION,
    curriculum: Curriculum.CBC,
    description: 'Christian/Islamic/Hindu Religious Education',
    gradeLevelStart: 6,
    gradeLevelEnd: 8,
    isCompulsory: false,
    lessonsPerWeek: 2,
  },
  {
    name: 'Creative Arts',
    code: 'CBC-CA-UP',
    category: SubjectCategory.ARTS,
    curriculum: Curriculum.CBC,
    description: 'Music, art, drama, and performing arts',
    gradeLevelStart: 6,
    gradeLevelEnd: 8,
    isCompulsory: true,
    lessonsPerWeek: 3,
  },
  {
    name: 'Physical and Health Education',
    code: 'CBC-PHE-UP',
    category: SubjectCategory.PHYSICAL_EDUCATION,
    curriculum: Curriculum.CBC,
    description: 'Sports, games, and physical fitness',
    gradeLevelStart: 6,
    gradeLevelEnd: 8,
    isCompulsory: true,
    lessonsPerWeek: 3,
  },

  // Junior Secondary (Grades 7-9, Levels 9-11)
  {
    name: 'English',
    code: 'CBC-ENG-JS',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.CBC,
    description: 'English language and literature',
    gradeLevelStart: 9, // Grade 7
    gradeLevelEnd: 11, // Grade 9
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Kiswahili/Kenyan Sign Language',
    code: 'CBC-KIS-JS',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.CBC,
    description: 'Kiswahili language and literature',
    gradeLevelStart: 9,
    gradeLevelEnd: 11,
    isCompulsory: true,
    lessonsPerWeek: 4,
  },
  {
    name: 'Mathematics',
    code: 'CBC-MATH-JS',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.CBC,
    description: 'Advanced mathematics',
    gradeLevelStart: 9,
    gradeLevelEnd: 11,
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Integrated Science',
    code: 'CBC-SCI-JS',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.CBC,
    description: 'Physics, Chemistry, Biology integration',
    gradeLevelStart: 9,
    gradeLevelEnd: 11,
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Health Education',
    code: 'CBC-HE-JS',
    category: SubjectCategory.LIFE_SKILLS,
    curriculum: Curriculum.CBC,
    description: 'Health, hygiene, and life skills',
    gradeLevelStart: 9,
    gradeLevelEnd: 11,
    isCompulsory: true,
    lessonsPerWeek: 2,
  },
  {
    name: 'Pre-Technical and Pre-Career Education',
    code: 'CBC-PTPCE-JS',
    category: SubjectCategory.TECHNICAL,
    curriculum: Curriculum.CBC,
    description: 'Career pathways and technical skills',
    gradeLevelStart: 9,
    gradeLevelEnd: 11,
    isCompulsory: true,
    lessonsPerWeek: 4,
  },
  {
    name: 'Social Studies',
    code: 'CBC-SS-JS',
    category: SubjectCategory.HUMANITIES,
    curriculum: Curriculum.CBC,
    description: 'History, geography, and citizenship',
    gradeLevelStart: 9,
    gradeLevelEnd: 11,
    isCompulsory: true,
    lessonsPerWeek: 3,
  },
  {
    name: 'Religious Education',
    code: 'CBC-RE-JS',
    category: SubjectCategory.RELIGIOUS_EDUCATION,
    curriculum: Curriculum.CBC,
    description: 'Christian/Islamic/Hindu Religious Education',
    gradeLevelStart: 9,
    gradeLevelEnd: 11,
    isCompulsory: false,
    lessonsPerWeek: 2,
  },
  {
    name: 'Business Studies',
    code: 'CBC-BUS-JS',
    category: SubjectCategory.BUSINESS,
    curriculum: Curriculum.CBC,
    description: 'Introduction to business and entrepreneurship',
    gradeLevelStart: 9,
    gradeLevelEnd: 11,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Agriculture',
    code: 'CBC-AGR-JS',
    category: SubjectCategory.TECHNICAL,
    curriculum: Curriculum.CBC,
    description: 'Agricultural practices and food security',
    gradeLevelStart: 9,
    gradeLevelEnd: 11,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Creative Arts and Sports',
    code: 'CBC-CAS-JS',
    category: SubjectCategory.ARTS,
    curriculum: Curriculum.CBC,
    description: 'Music, art, drama, and sports',
    gradeLevelStart: 9,
    gradeLevelEnd: 11,
    isCompulsory: true,
    lessonsPerWeek: 4,
  },
];

// 8-4-4 System Subjects
export const EIGHT_FOUR_FOUR_SUBJECTS: PredefinedSubject[] = [
  // Primary (Standards 1-8, Levels 3-10)
  {
    name: 'English',
    code: '844-ENG-PRI',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'English language',
    gradeLevelStart: 3,
    gradeLevelEnd: 10,
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Kiswahili',
    code: '844-KIS-PRI',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Kiswahili language',
    gradeLevelStart: 3,
    gradeLevelEnd: 10,
    isCompulsory: true,
    lessonsPerWeek: 4,
  },
  {
    name: 'Mathematics',
    code: '844-MATH-PRI',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Mathematics',
    gradeLevelStart: 3,
    gradeLevelEnd: 10,
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Science',
    code: '844-SCI-PRI',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Science and Agriculture',
    gradeLevelStart: 3,
    gradeLevelEnd: 10,
    isCompulsory: true,
    lessonsPerWeek: 4,
  },
  {
    name: 'Social Studies',
    code: '844-SS-PRI',
    category: SubjectCategory.HUMANITIES,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'History, Geography, CRE/IRE',
    gradeLevelStart: 3,
    gradeLevelEnd: 10,
    isCompulsory: true,
    lessonsPerWeek: 4,
  },
  {
    name: 'Christian Religious Education',
    code: '844-CRE-PRI',
    category: SubjectCategory.RELIGIOUS_EDUCATION,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Christian Religious Education',
    gradeLevelStart: 3,
    gradeLevelEnd: 10,
    isCompulsory: false,
    lessonsPerWeek: 2,
  },
  {
    name: 'Islamic Religious Education',
    code: '844-IRE-PRI',
    category: SubjectCategory.RELIGIOUS_EDUCATION,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Islamic Religious Education',
    gradeLevelStart: 3,
    gradeLevelEnd: 10,
    isCompulsory: false,
    lessonsPerWeek: 2,
  },
  {
    name: 'Hindu Religious Education',
    code: '844-HRE-PRI',
    category: SubjectCategory.RELIGIOUS_EDUCATION,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Hindu Religious Education',
    gradeLevelStart: 3,
    gradeLevelEnd: 10,
    isCompulsory: false,
    lessonsPerWeek: 2,
  },

  // Secondary (Forms 1-4, Levels 11-14) - But we only go to 13
  {
    name: 'English',
    code: '844-ENG-SEC',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'English language and literature',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Kiswahili',
    code: '844-KIS-SEC',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Kiswahili language',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: true,
    lessonsPerWeek: 4,
  },
  {
    name: 'Mathematics',
    code: '844-MATH-SEC',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Mathematics',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Biology',
    code: '844-BIO-SEC',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Biology',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 4,
  },
  {
    name: 'Chemistry',
    code: '844-CHEM-SEC',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Chemistry',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 4,
  },
  {
    name: 'Physics',
    code: '844-PHY-SEC',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Physics',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 4,
  },
  {
    name: 'History',
    code: '844-HIST-SEC',
    category: SubjectCategory.HUMANITIES,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'History and Government',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Geography',
    code: '844-GEO-SEC',
    category: SubjectCategory.HUMANITIES,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Geography',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Christian Religious Education',
    code: '844-CRE-SEC',
    category: SubjectCategory.RELIGIOUS_EDUCATION,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Christian Religious Education',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Islamic Religious Education',
    code: '844-IRE-SEC',
    category: SubjectCategory.RELIGIOUS_EDUCATION,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Islamic Religious Education',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Business Studies',
    code: '844-BUS-SEC',
    category: SubjectCategory.BUSINESS,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Business Studies',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Computer Studies',
    code: '844-COMP-SEC',
    category: SubjectCategory.TECHNICAL,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Computer Studies',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Home Science',
    code: '844-HS-SEC',
    category: SubjectCategory.TECHNICAL,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Home Science',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Agriculture',
    code: '844-AGR-SEC',
    category: SubjectCategory.TECHNICAL,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Agriculture',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Art & Design',
    code: '844-ART-SEC',
    category: SubjectCategory.ARTS,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Art and Design',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Music',
    code: '844-MUS-SEC',
    category: SubjectCategory.ARTS,
    curriculum: Curriculum.EIGHT_FOUR_FOUR,
    description: 'Music',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
];

// Cambridge IGCSE/A-Level Subjects
export const CAMBRIDGE_SUBJECTS: PredefinedSubject[] = [
  // IGCSE (Typically Grades 9-10, Levels 11-12)
  {
    name: 'English as a Second Language',
    code: 'CAM-ESL',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge IGCSE English as a Second Language',
    gradeLevelStart: 11,
    gradeLevelEnd: 12,
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Mathematics',
    code: 'CAM-MATH',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge IGCSE Mathematics',
    gradeLevelStart: 11,
    gradeLevelEnd: 12,
    isCompulsory: true,
    lessonsPerWeek: 5,
  },
  {
    name: 'Biology',
    code: 'CAM-BIO',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge IGCSE Biology',
    gradeLevelStart: 11,
    gradeLevelEnd: 12,
    isCompulsory: false,
    lessonsPerWeek: 4,
  },
  {
    name: 'Chemistry',
    code: 'CAM-CHEM',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge IGCSE Chemistry',
    gradeLevelStart: 11,
    gradeLevelEnd: 12,
    isCompulsory: false,
    lessonsPerWeek: 4,
  },
  {
    name: 'Physics',
    code: 'CAM-PHY',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge IGCSE Physics',
    gradeLevelStart: 11,
    gradeLevelEnd: 12,
    isCompulsory: false,
    lessonsPerWeek: 4,
  },
  {
    name: 'Business Studies',
    code: 'CAM-BUS',
    category: SubjectCategory.BUSINESS,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge IGCSE Business Studies',
    gradeLevelStart: 11,
    gradeLevelEnd: 12,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Economics',
    code: 'CAM-ECON',
    category: SubjectCategory.BUSINESS,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge IGCSE Economics',
    gradeLevelStart: 11,
    gradeLevelEnd: 12,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Computer Science',
    code: 'CAM-CS',
    category: SubjectCategory.TECHNICAL,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge IGCSE Computer Science',
    gradeLevelStart: 11,
    gradeLevelEnd: 12,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Geography',
    code: 'CAM-GEO',
    category: SubjectCategory.HUMANITIES,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge IGCSE Geography',
    gradeLevelStart: 11,
    gradeLevelEnd: 12,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'History',
    code: 'CAM-HIST',
    category: SubjectCategory.HUMANITIES,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge IGCSE History',
    gradeLevelStart: 11,
    gradeLevelEnd: 12,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },
  {
    name: 'Art & Design',
    code: 'CAM-ART',
    category: SubjectCategory.ARTS,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge IGCSE Art & Design',
    gradeLevelStart: 11,
    gradeLevelEnd: 12,
    isCompulsory: false,
    lessonsPerWeek: 3,
  },

  // A-Level (Typically Grades 11-12, Levels 12-13)
  {
    name: 'A-Level Mathematics',
    code: 'CAM-MATH-AL',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge A-Level Mathematics',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 6,
  },
  {
    name: 'A-Level Further Mathematics',
    code: 'CAM-FMATH-AL',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge A-Level Further Mathematics',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 6,
  },
  {
    name: 'A-Level Physics',
    code: 'CAM-PHY-AL',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge A-Level Physics',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 6,
  },
  {
    name: 'A-Level Chemistry',
    code: 'CAM-CHEM-AL',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge A-Level Chemistry',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 6,
  },
  {
    name: 'A-Level Biology',
    code: 'CAM-BIO-AL',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge A-Level Biology',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 6,
  },
  {
    name: 'A-Level Economics',
    code: 'CAM-ECON-AL',
    category: SubjectCategory.BUSINESS,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge A-Level Economics',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 5,
  },
  {
    name: 'A-Level Computer Science',
    code: 'CAM-CS-AL',
    category: SubjectCategory.TECHNICAL,
    curriculum: Curriculum.CAMBRIDGE,
    description: 'Cambridge A-Level Computer Science',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 5,
  },
];

// IB (International Baccalaureate) Subjects
export const IB_SUBJECTS: PredefinedSubject[] = [
  // IB Diploma Programme (Grades 11-12, Levels 12-13)
  {
    name: 'IB English A: Language and Literature',
    code: 'IB-ENG-A',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.IB,
    description: 'IB English A: Language and Literature (HL/SL)',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: true,
    lessonsPerWeek: 5,
    credits: 6,
  },
  {
    name: 'IB Mathematics: Analysis and Approaches',
    code: 'IB-MATH-AA',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.IB,
    description: 'IB Mathematics: Analysis and Approaches (HL/SL)',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 5,
    credits: 6,
  },
  {
    name: 'IB Mathematics: Applications and Interpretation',
    code: 'IB-MATH-AI',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.IB,
    description: 'IB Mathematics: Applications and Interpretation (HL/SL)',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 5,
    credits: 6,
  },
  {
    name: 'IB Biology',
    code: 'IB-BIO',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.IB,
    description: 'IB Biology (HL/SL)',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 5,
    credits: 6,
  },
  {
    name: 'IB Chemistry',
    code: 'IB-CHEM',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.IB,
    description: 'IB Chemistry (HL/SL)',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 5,
    credits: 6,
  },
  {
    name: 'IB Physics',
    code: 'IB-PHY',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.IB,
    description: 'IB Physics (HL/SL)',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 5,
    credits: 6,
  },
  {
    name: 'IB History',
    code: 'IB-HIST',
    category: SubjectCategory.HUMANITIES,
    curriculum: Curriculum.IB,
    description: 'IB History (HL/SL)',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 4,
    credits: 6,
  },
  {
    name: 'IB Geography',
    code: 'IB-GEO',
    category: SubjectCategory.HUMANITIES,
    curriculum: Curriculum.IB,
    description: 'IB Geography (HL/SL)',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 4,
    credits: 6,
  },
  {
    name: 'IB Economics',
    code: 'IB-ECON',
    category: SubjectCategory.BUSINESS,
    curriculum: Curriculum.IB,
    description: 'IB Economics (HL/SL)',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 4,
    credits: 6,
  },
  {
    name: 'IB Business Management',
    code: 'IB-BUS',
    category: SubjectCategory.BUSINESS,
    curriculum: Curriculum.IB,
    description: 'IB Business Management (HL/SL)',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 4,
    credits: 6,
  },
  {
    name: 'IB Computer Science',
    code: 'IB-CS',
    category: SubjectCategory.TECHNICAL,
    curriculum: Curriculum.IB,
    description: 'IB Computer Science (HL/SL)',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 4,
    credits: 6,
  },
  {
    name: 'IB Visual Arts',
    code: 'IB-ART',
    category: SubjectCategory.ARTS,
    curriculum: Curriculum.IB,
    description: 'IB Visual Arts (HL/SL)',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 4,
    credits: 6,
  },
  {
    name: 'IB Theory of Knowledge',
    code: 'IB-TOK',
    category: SubjectCategory.HUMANITIES,
    curriculum: Curriculum.IB,
    description: 'IB Theory of Knowledge (Core)',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: true,
    lessonsPerWeek: 2,
    credits: 3,
  },
];

// American Curriculum Subjects
export const AMERICAN_SUBJECTS: PredefinedSubject[] = [
  // High School (Grades 9-12, Levels 11-13+)
  {
    name: 'English Language Arts',
    code: 'US-ELA',
    category: SubjectCategory.LANGUAGE,
    curriculum: Curriculum.AMERICAN,
    description: 'English Language Arts (Reading, Writing, Literature)',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: true,
    lessonsPerWeek: 5,
    credits: 4,
  },
  {
    name: 'Algebra I',
    code: 'US-ALG1',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.AMERICAN,
    description: 'Algebra I',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: true,
    lessonsPerWeek: 5,
    credits: 4,
  },
  {
    name: 'Geometry',
    code: 'US-GEO',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.AMERICAN,
    description: 'Geometry',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 5,
    credits: 4,
  },
  {
    name: 'Algebra II',
    code: 'US-ALG2',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.AMERICAN,
    description: 'Algebra II',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 5,
    credits: 4,
  },
  {
    name: 'Pre-Calculus',
    code: 'US-PRECALC',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.AMERICAN,
    description: 'Pre-Calculus',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 5,
    credits: 4,
  },
  {
    name: 'AP Calculus AB',
    code: 'US-CALC-AB',
    category: SubjectCategory.MATHEMATICS,
    curriculum: Curriculum.AMERICAN,
    description: 'AP Calculus AB',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 5,
    credits: 5,
  },
  {
    name: 'Biology',
    code: 'US-BIO',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.AMERICAN,
    description: 'Biology',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: true,
    lessonsPerWeek: 5,
    credits: 4,
  },
  {
    name: 'Chemistry',
    code: 'US-CHEM',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.AMERICAN,
    description: 'Chemistry',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 5,
    credits: 4,
  },
  {
    name: 'Physics',
    code: 'US-PHY',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.AMERICAN,
    description: 'Physics',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 5,
    credits: 4,
  },
  {
    name: 'AP Biology',
    code: 'US-BIO-AP',
    category: SubjectCategory.SCIENCE,
    curriculum: Curriculum.AMERICAN,
    description: 'AP Biology',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 6,
    credits: 5,
  },
  {
    name: 'US History',
    code: 'US-HIST',
    category: SubjectCategory.HUMANITIES,
    curriculum: Curriculum.AMERICAN,
    description: 'United States History',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: true,
    lessonsPerWeek: 4,
    credits: 4,
  },
  {
    name: 'World History',
    code: 'US-WHIST',
    category: SubjectCategory.HUMANITIES,
    curriculum: Curriculum.AMERICAN,
    description: 'World History',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 4,
    credits: 4,
  },
  {
    name: 'Economics',
    code: 'US-ECON',
    category: SubjectCategory.BUSINESS,
    curriculum: Curriculum.AMERICAN,
    description: 'Economics',
    gradeLevelStart: 12,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 3,
    credits: 3,
  },
  {
    name: 'Computer Science',
    code: 'US-CS',
    category: SubjectCategory.TECHNICAL,
    curriculum: Curriculum.AMERICAN,
    description: 'Computer Science',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 4,
    credits: 4,
  },
  {
    name: 'Physical Education',
    code: 'US-PE',
    category: SubjectCategory.PHYSICAL_EDUCATION,
    curriculum: Curriculum.AMERICAN,
    description: 'Physical Education',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: true,
    lessonsPerWeek: 3,
    credits: 2,
  },
  {
    name: 'Visual Arts',
    code: 'US-ART',
    category: SubjectCategory.ARTS,
    curriculum: Curriculum.AMERICAN,
    description: 'Visual Arts',
    gradeLevelStart: 11,
    gradeLevelEnd: 13,
    isCompulsory: false,
    lessonsPerWeek: 3,
    credits: 3,
  },
];

// Export all subjects combined
export const ALL_PREDEFINED_SUBJECTS = [
  ...CBC_SUBJECTS,
  ...EIGHT_FOUR_FOUR_SUBJECTS,
  ...CAMBRIDGE_SUBJECTS,
  ...IB_SUBJECTS,
  ...AMERICAN_SUBJECTS,
];